#!/bin/bash -l
#PBS -A eic
#PBS -N CutEvent

#PBS -l select=1:ncpus=128
#PBS -l walltime=12:00:00
#PBS -j oe

#PBS -m bea
#PBS -M tgibbons@anl.gov

cd /lcrc/project/eic/tgibbons/G4ChargeExchange/build/

module load root
export LD_LIBRARY_PATH=/lcrc/project/eic/tgibbons/xxhash-install/lib:$LD_LIBRARY_PATH

echo Jobid: $PBS_JOBID
echo Running on host `hostname`
echo Running on nodes `cat $PBS_NODEFILE`

./sim 1000.mac