
/run/initialize

#Detector
/detector/nCols 501
/detector/nRows 501
/detector/nCols_detector 501
/detector/nRows_detector 501
#/detector/nBlocks
#/detector/randPosDetector
#/detector/randPosScaling
/run/reinitializeGeometry

#Paritcle Position
#/randGun/randPAngle
#/randGun/randPos

#Folder
/output/folder MacroTest_output/501

#Polarization
/Polarization/PPIndex 7
/Polarization/PrintPPIndex

/run/beamOn 100000
