
/run/initialize

#Detector
/detector/nCols 451
/detector/nRows 451
/detector/nCols_detector 451
/detector/nRows_detector 451
#/detector/nBlocks
#/detector/randPosDetector
#/detector/randPosScaling
/run/reinitializeGeometry

#Paritcle Position
#/randGun/randPAngle
#/randGun/randPos

#Folder
/output/folder MacroTest_output/451

#Polarization
/Polarization/PPIndex 7
/Polarization/PrintPPIndex

/run/beamOn 100000
