
/run/initialize

#Detector
/detector/nCols 251
/detector/nRows 251
/detector/nCols_detector 251
/detector/nRows_detector 251
#/detector/nBlocks
#/detector/randPosDetector
#/detector/randPosScaling
/run/reinitializeGeometry

#Paritcle Position
#/randGun/randPAngle
#/randGun/randPos

#Folder
/output/folder MacroTest_output/251

#Polarization
/Polarization/PPIndex 7
/Polarization/PrintPPIndex

/run/beamOn 100000
